# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokiburi < Formula
  desc "Automatic test runs for Go projects"
  homepage "https://github.com/michenriksen/gokiburi"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/michenriksen/gokiburi/releases/download/v0.1.3/gokiburi_Darwin_arm64.tar.gz"
      sha256 "b6ca3e76fd69476bc2bd6f1dc0106f4eb553e97822e45b9474c59c6e2ec28563"

      def install
        bin.install "gokiburi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/michenriksen/gokiburi/releases/download/v0.1.3/gokiburi_Darwin_x86_64.tar.gz"
      sha256 "7f0b204f517c7235d363d095951843a42390bbb9c2e66dc20ee2dbc3ab63349c"

      def install
        bin.install "gokiburi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michenriksen/gokiburi/releases/download/v0.1.3/gokiburi_Linux_arm64.tar.gz"
      sha256 "245ec2d977352c11e7e80738b795502a2724d0e97ba844b4004fc6013106006d"

      def install
        bin.install "gokiburi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/michenriksen/gokiburi/releases/download/v0.1.3/gokiburi_Linux_x86_64.tar.gz"
      sha256 "5ab6484ce32fb3992f66d8de703c88a9570acef41ffdd3f0fc3a59689985eb61"

      def install
        bin.install "gokiburi"
      end
    end
  end

  test do
    system "#{bin}/gokiburi --version"
  end
end
