# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokiburi < Formula
  desc "Automatic test runs for Go projects"
  homepage "https://github.com/michenriksen/gokiburi"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/michenriksen/gokiburi/releases/download/v0.2.1/gokiburi_Darwin_arm64.tar.gz"
      sha256 "eec19cd0e6df651bf411db13da9e4cc3d45a3669bddb07d4a0462f19ac032cd8"

      def install
        bin.install "gokiburi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/michenriksen/gokiburi/releases/download/v0.2.1/gokiburi_Darwin_x86_64.tar.gz"
      sha256 "ebbcf11f514e548e06c52c120d4068d9c34d0b8c3a7645262be51be3773aad75"

      def install
        bin.install "gokiburi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/michenriksen/gokiburi/releases/download/v0.2.1/gokiburi_Linux_arm64.tar.gz"
      sha256 "f73a7e7d3d10ae3735e9d85ee584d98ed02123bf12de0f46ee495d42603ef3b3"

      def install
        bin.install "gokiburi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/michenriksen/gokiburi/releases/download/v0.2.1/gokiburi_Linux_x86_64.tar.gz"
      sha256 "8ffc46aa9190289c067a4216524cbc9dc2d3ae2ffcbcf5ae9a3808539f86f28f"

      def install
        bin.install "gokiburi"
      end
    end
  end

  test do
    system "#{bin}/gokiburi --version"
  end
end
